server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
  profiles:
    active: native

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot: DEBUG 